# Generated by Django 4.2.2 on 2023-07-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App2", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClickCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name="Photo",
        ),
    ]
