# Generated by Django 5.0.1 on 2024-02-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App2', '0002_clickcount_delete_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenPathMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=255, unique=True)),
                ('token', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
