# Generated by Django 5.0.4 on 2024-05-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App2', '0003_tokenpathmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickcount',
            name='username',
            field=models.CharField(default='User', max_length=256),
        ),
    ]
